# Generated by Django 5.2.6 on 2025-09-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_employeeeducation_employeeexperience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeexperience',
            old_name='company1design',
            new_name='company1desig',
        ),
        migrations.RenameField(
            model_name='employeeexperience',
            old_name='company2design',
            new_name='company2desig',
        ),
        migrations.RenameField(
            model_name='employeeexperience',
            old_name='company3design',
            new_name='company3desig',
        ),
        migrations.RemoveField(
            model_name='employeeeducation',
            name='schoolclhsc',
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='schoolclghsc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='company4desig',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='company4duration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='company4name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='company4salary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='percentagegra',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='percentagehsc',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='percentagepg',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='percentagessc',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='schoolclggra',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='schoolclgpg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='yearofpassinggra',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='yearofpassinghsc',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='yearofpassingpg',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='yearofpassingssc',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
